language: python
python:
- "3.6"
- "3.7"
- "3.8"

notifications:
  email: false

install:
  - pip install -r requirements.txt
env:
  - TEST_SUITE=test
  - TEST_SUITE=test_all
script:
  - make $TEST_SUITE
  - make install

# Push the results back to codecov
after_success:
  - codecov
