language: python
python:
- "2.7"
- "3.4"
- "3.7"

notifications:
  email: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Install python environment and dependencies
  - conda install --yes python=$CONDA_PY --file requirements.txt
  # Install codecov integration
  - pip install codecov pytest-cov


install:
  # run tests with coverage information
  - pip install -r requirements
  - py.test --cov=./

after_success:
  - codecov
